version: '2'
services:
  app:
    container_name: bookshop
    build: .
    ports:
      - '3000:3000'
    restart: always
    command: npm start
    depends_on: 
        - mysql
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - '--name=bookshop-mysql'
    volumes:
      - './mysqldata:/var/lib/mysql'
    ports:
      - '3306:3306'
